### ISSUE TITLE
stepper motor library feedback to pc

### ISSUE THREAD

**Issue by FineLineAutomation** [firmata/arduino#125]
Is there a mechanism in the stepper motor library to communicate back to the PC how many steps the stepper motor has moved? Trying to implement a live updated DRO on the PC side.

**Comment by DomAmato** [comment]
Again a bit late to the party here but from my understanding the stepper implementation @soundanalogous made has a step counter which I used to get the current position though it zeros itself with a new move command. It works for what I needed to do since i was moving in 16th steps so missing a few wasn't the end of the world.

https://github.com/DomAmato/Robust-Firmata

**Comment by soundanalogous** [comment]
One option here would be to add a Stop message to the Stepper protocol but that would be to slow to call externally in most cases (still a convenience none the less). Also you could provide a pin number to watch and an edge (high / low) - do you need just one or does this take 2 pins (I've never implemented this sort of thing with a Stepper before)? If the edge changes as specified on that pin then call stop() (to be added) on the stepper internally. This pin(s) would need to be added after the optional motor pins. I'm not exactly sure how to do that yet without specifically indicating the total number of motor pins for the case where the user is only using 2 pins rather than 4 (there are free bits in bytes 2 and 3 that could be used to indicate this).

**Comment by soundanalogous** [comment]
Just realized I had changed the upper bytes of the Interface command to [set the step delay](https://github.com/soundanalogous/AdvancedFirmata/blob/master/FirmataStepper.cpp#L88-L97) (to support high current drivers that need a 2us delay rather than the standard 1us delay between steps). I need to update this in the Stepper protocol. That leaves me to find another place to indicate if there are feedback pins...

**Comment by DomAmato** [comment]
Yeah my implementation wasn't particularly pretty, I think it should probably check the length of argc too to make sure that all the values are actually given. perhaps adding to the interface where 8 means feedback and then & 0x07 to figure out the interface type something like this:

    enum Interface {
		DRIVER = 1,
		TWO_WIRE = 2,
		FOUR_WIRE = 4,
		HAS_FEEDBACK = 8
	};

so that 

    if(interfaceType & 0x08)
       we have feedback pins
      if(interfaceType & 0x07 == Stepper::DRIVER) ...
    else {
       we don't have feedback pins
    }

**Comment by soundanalogous** [comment]
The issue here is that only the lower 3 bits of that byte are available. I'm using the upper 4 bits to specify the step delay. I had forgot to add that to the protocol, but [it's there now](https://github.com/firmata/protocol/blob/master/stepper.md#protocol). However there are free bits in bytes 2 and 3 (CONFIG and DEVICE_NUMBER) so the hasFeedback flag could go there. This protocol is going to get messy. It really needs to be done differently but I got very little feedback on it when I first created it a couple of years ago (few people were watching Firmata at that time). Now there are at least 3 popular Firmata client libraries using the Stepper protocol so to break compatibility may be a bigger mess than butchering the existing protocol.

**Comment by soundanalogous** [comment]
Also the INTERFACE command is the only byte that had bits available that gets passed all the way through to FirmataStepper so the stepDelay has to be applied OR'd with that byte since it needs to be set within the FirmataStepper library constructor. CONFIG and DEVICE_NUMBER are handled at the next higher layer (AdvancedFirmata, RobustFirmata, ConfigurableFirmata) so that would be a better place for the hasFeedback flag since you would handle it at that level.

**Comment by soundanalogous** [comment]
I guess I could reserve the 7th bit of interface for the hasFeedback flag. It would limit the amount number of stepDelay values that can be set in the future to 2 bits (4 values). It's ugly but the Interface byte could be split like this:

bits 0-3: INTERFACE 
bits 4-5: STEP_DELAY
bits 6: HAS_FEEDBACK

This would maintain backwards compatibility with existing Stepper implementations.

**Comment by soundanalogous** [comment]
correction, it would look like this:

bits 0-2: INTERFACE
bits 3-5: STEP_DELAY
bit 6: HAS_FEEDBACK

Which leaves 4 values for step delay.

**Comment by DomAmato** [comment]
Works for me, since the step delay is just a floor value unless I am misinterpreting that. There could be a separate protocol to set a max speed. I was looking at accelStepper though actually liked your library better for its brevity but the step delay would be then used like this right:

    _step_delay = max(_min_step_delay, _step_delay);

**Comment by soundanalogous** [comment]
The step delay value is used here: https://github.com/soundanalogous/FirmataStepper/blob/master/FirmataStepper.cpp#L381-L388. It only applies to step + direction type drivers. Some high current drivers need at least a 2 microsecond delay. There may be other variants needed in the future as well, but so far the 2us delay has fixed any reported issues with high current drivers.

**Comment by soundanalogous** [comment]
Re accelStepper, I was originally considering wrapping that library but it had too many features and consumed too much memory - at least when you need to support a bunch of other potential features simultaneously. I think it also had a few lengthy delay calls in the code which I am keen to avoid for Firmata features. accelStepper is a much better written library than FirmataStepper though. I implemented FirmataStepper based on a white paper I came across. I still don't fully understand all the math involved. Someday I hope some much smarter than me picks it up and improves it :)

**Comment by soundanalogous** [comment]
Just took a look at accelStepper again for the first time in a long while. It's actually much simpler than I remember. Not sure why I chose to write FirmataStepper over just wrapping accelStepper. I mush have had some reason a couple of years ago. I don't see any delays other than the step delay so that couldn't be the reason. I don't think it would consume much more memory than FirmataStepper either now that I'm looking over the code again. Strange.

**Comment by DomAmato** [comment]
I think you implement the formulas better though which I believe you got from this:
http://www.hwml.com/LeibRamp.pdf 
which is based off of this:
http://fab.cba.mit.edu/classes/MIT/961.09/projects/i0/Stepper_Motor_Speed_Profile.pdf

**Comment by soundanalogous** [comment]
I remember looking over the two papers you referenced, but ultimately I used this paper: http://www.atmel.com/Images/doc8017.pdf and the accompanying sample code also published by Atmel. All share some similar logic.

**Comment by DomAmato** [comment]
Yeah they all seem to be based off the same set of equations. I remember now why I ended up using FirmataStepper over the AccelStepper and it had to do with the run() and runSpeed(). Run was never able to go at the max speed or same speed that runSpeed() did even if the numbers were set the same. I probably should have investigated more as to why this was happening but at the time I needed results and defaulted to the one that was behaving as I needed it to. This was done with a Nema 17 and 23 type stepper using the A4988 stepper driver at 8th and 16th steps.

**Comment by soundanalogous** [comment]
This issue was moved to firmata/ConfigurableFirmata#2
