### ISSUE TITLE
any plans to support OneWire on Edison break out board?

### ISSUE THREAD

**Issue by akulo** [firmata/arduino#216]

**Comment by rwaldron** [comment]
Are you referring to this?

![](https://cdn.sparkfun.com//assets/parts/1/0/1/3/9/13097-06.jpg)

If yes, then this isn't the right place to file this issue, as Firmata isn't used on that breakout, because it's not actually an "Arduino" in the microcontroller sense. It's a linux SBC with GPIO connected to pin outs that only "look like" an Arduino's pin outs.

**Comment by soundanalogous** [comment]
First someone needs to write an OneWire library that runs on the Edison.
