### ISSUE TITLE
variable limit on pro mini

### ISSUE THREAD

**Issue by TheYkk** [firmata/arduino#416]
i want install firmata plus but i get error veriable limit 1024 byte

```Sketch uses 15202 bytes (106%) of program storage space. Maximum is 14336 bytes.
Global variables use 1274 bytes (124%) of dynamic memory, leaving -250 bytes for local variables. Maximum is 1024 bytes.
Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
Error compiling for board Arduino Pro or Pro Mini.
```

**Comment by soundanalogous** [comment]
It looks like you have an older Pro Mini which used the ATmega168 rather than the ATmega328 that you'd find in a newer Pro Mini. The ATmega168 only has 1 KB of RAM, but StandardFirmataPlus consumes 1.27 KB. StandardFirmata (not Plus) may fit within 1 KB but it could give you troubles since nearly all the RAM would be utilized.

**Comment by TheYkk** [comment]
thx
